//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class grupo
    {
        public grupo()
        {
            this.perfil = new HashSet<perfil>();
            this.usuario = new HashSet<usuario>();
        }
    
        public string gru_codigo { get; set; }
        public string gru_descripcion { get; set; }
        public bool gru_estado { get; set; }
    
        public virtual ICollection<perfil> perfil { get; set; }
        public virtual ICollection<usuario> usuario { get; set; }
    }
}
