//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class perfil
    {
        public perfil()
        {
            this.permiso = new HashSet<permiso>();
        }
    
        public int per_codigo { get; set; }
    
        public virtual formulario formulario { get; set; }
        public virtual grupo grupo { get; set; }
        public virtual ICollection<permiso> permiso { get; set; }
    }
}
