//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MODELO
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso
    {
        public permiso()
        {
            this.perfil = new HashSet<perfil>();
            this.formulario = new HashSet<formulario>();
        }
    
        public string per_codigo { get; set; }
        public string per_descripcion { get; set; }
    
        public virtual ICollection<perfil> perfil { get; set; }
        public virtual ICollection<formulario> formulario { get; set; }
    }
}
